"""v0.10.6 add domain.endDay server default

Revision ID: 344144652f30
Revises: 88abfa98c388
Create Date: 2020-10-14 18:04:35.611415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '344144652f30'
down_revision = '88abfa98c388'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('domains', 'end_day',
               existing_type=sa.DATE(),
               server_default='3333-03-03',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('domains', 'end_day',
               existing_type=sa.DATE(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###
